const data = {
    products: [
        {
            id: 1,
            name: 'Free Shirt',
            slug: 'free-shirt',
            category: 'Shirts',
            image: '/images/shirt1.jpg',
            price: 70,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular shirt',
        },
        {
            id: 2,
            name: 'Fit Shirt',
            slug: 'fit-shirt',
            category: 'Shirts',
            image: '/images/shirt2.jpg',
            price: 80,
            brand: 'Adidas',
            rating: 4.2,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular shirt',
        },
        {
            id: 3,
            name: 'Slim Shirt',
            slug: 'slim-shirt',
            category: 'Shirts',
            image: '/images/shirt3.jpg',
            price: 90,
            brand: 'Raymond',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular shirt',
        },
        {
            id: 4,
            name: 'Golf Pants',
            slug: 'golf-pants',
            category: 'Pants',
            image: '/images/pants1.jpg',
            price: 70,
            brand: 'Oliver',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'Smart looking pants',
        },
        {
            id: 5,
            name: 'Fit Pant',
            slug: 'fit-pant',
            category: 'Pants',
            image: '/images/pants2.jpg',
            price: 95,
            brand: 'Jara',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular Pant',
        },
        {
            id: 6,
            name: 'Pant',
            slug: 'pant',
            category: 'Shirts',
            image: '/images/pants3.jpg',
            price: 75,
            brand: 'Casely',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular Pant',
        },
    ],
};
export default data;